Add vision
Team-2502/RobotCode2019 pull request #14
Opened 2019-02-20 13:15 UTC by ritikmishra

Very important

2019-02-20 17:46 UTC, andrewgazelka commented on src/main/java/com/team2502/robot2019/Robot.java
>          PPWaypoint[] waypoints = new PPWaypoint.Builder()
I think we should have a separate class which has a bunch of these tests so we can more easily organize them.

2019-02-20 18:10 UTC, andrewgazelka requested changes

2019-02-20 18:10 UTC, andrewgazelka commented on src/main/java/com/team2502/robot2019/Robot.java
>          PPWaypoint[] waypoints = new PPWaypoint.Builder()
I think we should have a separate class which has a bunch of these tests so we can more easily organize them.

2019-02-20 18:10 UTC, andrewgazelka commented on src/main/java/com/team2502/robot2019/RobotMap.java
> +            public static final int BUTTON_AUTO = 1;
what does the button do _for_ auto? Does it stop/start it? Please Specify

2019-02-20 18:10 UTC, andrewgazelka commented on src/main/java/com/team2502/robot2019/command/autonomous/ingredients/VelocityDriveCommand.java
> +    private int apple = 0;
probably not the best variable names @ritikmishra  :p

2019-02-20 18:10 UTC, andrewgazelka commented on src/main/java/com/team2502/robot2019/command/vision/GoToTargetCommand.java
> +            DriverStation.reportError("Failed to create socket (whoops 3 potential precursor)", e.getStackTrace());
I feel like we should still let the exception be thrown.... don't we not want the rest of the command to run if there is an exception or will not catching the exception completely kill the robot? I remember something along these lines with the subsystem require system I was building in `ezAuton` ... I'm surprised it would kill the whole robot though (esp since `ezAuton` runs on another thread).

2019-02-20 18:10 UTC, andrewgazelka commented on src/main/java/com/team2502/robot2019/command/vision/GoToTargetCommand.java
> +            DriverStation.reportError("Null pointer in sockets (whoops 3)", e.getStackTrace());
look at above comment

2019-02-20 18:10 UTC, andrewgazelka commented on src/main/java/com/team2502/robot2019/command/vision/GoToTargetCommand.java
> +            if(strategy != null)  System.out.println("strategpgp = " + strategy.getGoalPoint());
look at above comment

2019-02-20 18:10 UTC, andrewgazelka commented on src/main/java/com/team2502/robot2019/command/vision/GoToTargetCommand.java
> +        PurePursuitMovementStrategy strategy = null;
kinda messy imo

2019-02-20 18:10 UTC, andrewgazelka commented on src/main/java/com/team2502/robot2019/subsystem/DrivetrainSubsystem.java
> +    private double kP = 0.2;
Should these be in the CONSTANTS class?

2019-02-20 18:18 UTC, isaacaj commented on src/main/java/com/team2502/robot2019/Robot.java
>          PPWaypoint[] waypoints = new PPWaypoint.Builder()
Is there an easy way to do this while also catching the exceptions where they occur so as not to break robot code?

2019-02-20 18:19 UTC, ritikmishra commented on src/main/java/com/team2502/robot2019/subsystem/DrivetrainSubsystem.java
> +    private double kP = 0.2;
No. They are not constant.

2019-02-20 18:22 UTC, andrewgazelka commented on src/main/java/com/team2502/robot2019/Robot.java
>          PPWaypoint[] waypoints = new PPWaypoint.Builder()
> Is there an easy way to do this while also catching the exceptions where they occur so as not to break robot code?

so exceptions in commands do cause robot code to restart, right?

2019-02-20 18:25 UTC, andrewgazelka commented on src/main/java/com/team2502/robot2019/subsystem/DrivetrainSubsystem.java
> +    private double kP = 0.2;
I see there are setters for `k{P,I,D}`, but I still think initial values should be stored in `Constants` there isn't much reason to change them anyway (unless for some unit-test-like-thing), right? I mean we only have one gear...

2019-02-20 19:25 UTC, ryandalex1 commented on src/main/java/com/team2502/robot2019/command/vision/GoToTargetCommand.java
> +            DriverStation.reportError("Failed to create socket (whoops 3 potential precursor)", e.getStackTrace());
Can we not just kill the command if the exception is thrown by setting isFinished to true?

2019-02-20 19:27 UTC, andrewgazelka commented on src/main/java/com/team2502/robot2019/command/vision/GoToTargetCommand.java
> +            DriverStation.reportError("Failed to create socket (whoops 3 potential precursor)", e.getStackTrace());
well `ezAuton` uses actions and I can definitely make it just end the action without crashing the robot if I know it actually _does_ end the action, but I am waiting for confirmation if this is true.

2019-02-20 19:34 UTC, isaacaj commented on src/main/java/com/team2502/robot2019/Robot.java
>          PPWaypoint[] waypoints = new PPWaypoint.Builder()
Yes. If not caught, exception will restart robot code.

2019-02-20 19:36 UTC, ritikmishra commented on src/main/java/com/team2502/robot2019/command/vision/GoToTargetCommand.java
> +            DriverStation.reportError("Failed to create socket (whoops 3 potential precursor)", e.getStackTrace());
I can test this Thurs

2019-02-20 19:37 UTC, andrewgazelka commented on src/main/java/com/team2502/robot2019/command/vision/GoToTargetCommand.java
> +            DriverStation.reportError("Failed to create socket (whoops 3 potential precursor)", e.getStackTrace());
does anyone know if this ever occurred with ezAuton actions?

2019-02-20 19:37 UTC, ritikmishra commented on src/main/java/com/team2502/robot2019/command/vision/GoToTargetCommand.java
> +        PurePursuitMovementStrategy strategy = null;
How would you clean it up?

2019-02-20 19:37 UTC, ritikmishra commented on src/main/java/com/team2502/robot2019/subsystem/DrivetrainSubsystem.java
> +    private double kP = 0.2;
I suppose

2019-02-20 19:40 UTC, andrewgazelka commented on src/main/java/com/team2502/robot2019/command/vision/GoToTargetCommand.java
> +        PurePursuitMovementStrategy strategy = null;
just the whole class in general... a lot of catching of exceptions and and then just (essentially) ignoring them... really hard to read. If you want to talk after class about this in person (or Discord) I'd be down to do that.

2019-02-20 19:48 UTC, andrewgazelka commented on src/main/java/com/team2502/robot2019/Robot.java
>          PPWaypoint[] waypoints = new PPWaypoint.Builder()
alright... I think we should really move to mostly using actions then.

2019-02-20 22:55 UTC, ryandalex1 commented on src/main/java/com/team2502/robot2019/RobotMap.java
> +            public static final int BUTTON_AUTO = 1;
Changed to BUTTON_ENABLE_AUTO_ALIGN

2019-03-10 06:08 UTC, ritikmishra commented
Obsoleted by #21

2019-03-10 06:08 UTC, closed without merging